config/routes.rb
Rails.application.routes.draw do
  
  get 'rss/index'
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  resources :projects
  resources :posts

	get 'posts/%{title}/show', to: 'posts#show'
	get 'feeds', to: "rss#index", format: 'rss'
	root 'posts#index'
	get '/contact' => 'static_pages#contact'
	get '/about' => 'static_pages#about'
	devise_scope :user do
		get '/admin' => 'devise/sessions#new'
	end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Dragonfly

  dragonfly_accessor :data, app: :ckeditor
  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  validates_property :ext, of: :data, in: attachment_file_types unless attachment_file_types.empty?

  def url_thumb
    Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  validates_property :format, of: :data, in: image_file_types unless image_file_types.empty?
  validates_property :image?, of: :data, as: true, message: :invalid

  def url_content
    data.thumb('800x800>').url
  end

  def url_thumb
    data.thumb('118x100#').url(url_thumb_options)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post, counter_cache: true
end

app/models/post.rb
class Post < ApplicationRecord
	#scope :mostcommented, order('comments_count DESC')
	scope :most_commented, -> {
  	order('comments_count DESC')
	}
	belongs_to :user
	has_many :comments, dependent: :destroy
	validates :title, presence: true, length: {minimum:5}
	validates :body, presence: true
	has_rich_text :body
	mount_uploader :top_picture, TopPictureUploader
end

app/models/project.rb
class Project < ApplicationRecord
	belongs_to :user
	mount_uploader :project_picture, ProjectPictureUploader
end

app/models/user.rb
class User < ApplicationRecord
	has_many :posts
	has_many :projects
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.paginate(:page => params[:page], :per_page => 5).order("created_at DESC")
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @user = current_user
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :top_picture, :anouncement)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all.order("created_at DESC")
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @user = @project.user.email
  end

  # GET /projects/new
  def new
    @project = current_user.projects.build
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.projects.build(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_path, notice: 'Post was successfully created.' }
        # format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        # format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to projects_path, notice: 'project was successfully updated.' }
        # format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        # format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_path, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :description, :github, :demo, :project_picture)
    end
end

app/controllers/rss_controller.rb
class HomeController < ApplicationController
  layout false

  def index
    @posts = Post.order(created_at: :desc)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def index
		
	end

	def about
		
	end

	def contact
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def markdown(source)
    Kramdown::Document.new(source).to_html.html_safe
  end

  def main_title
  	if params[:controller] == "posts"
  		"letters"
  	elsif params[:controller] == "projects"
  		"addiction"
  	elsif params[:controller] == "static_pages" && params[:action] == "about"
  		"myself"
  	else
  		""
  	end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper

end

app/helpers/projects_helper.rb
module ProjectsHelper
	def adaptive_height
  	projects = Project.all
  	height = (200*((projects.count + 4) / 4).to_i).to_s + "px"
  end
end

app/helpers/rss_helper.rb
module RssHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Ternow | <%= main_title %></title>
		<%= csrf_meta_tags %>
		<%= csp_meta_tag %>
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link href="/feeds" rel="alternate" title="RSS feed" type="application/rss+xml">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
		<%= stylesheet_link_tag    'application' %>
		<%= javascript_include_tag 'application' %>
	</head>

	<body>

		<header>
			<div class="header-image-title">
				<h1><%= main_title %></h1>
			</div>
			<div class="cover-image <%= main_title %>" style="">
				<div class="cover-image-overlay">
				</div>
			</div>
		</header>

	
		
<%= render 'layouts/header' %>

		<div class="container">

			<% if user_signed_in? %>
			<p>now online as: <%= current_user.email %></p>
			<p><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></p>
			<% end %>
			<%= yield %>
		</div>

	</body>
</html>

app/views/posts/_aside.html.erb
<aside class="col-md-6 aside-blog">


  <h2>Most commented</h2>
  <% @most_commented.each do |post| %>
    <h4><%= link_to post.title, post %></h4>
  <% end %>


</aside>

app/views/posts/_form.html.erb
<%= simple_form_for @post, html: { multipart: true } do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.input :title, input_html: { class: 'form-control' } %>
  </div>
  
  <div class="field">
    <%= form.input :anouncement, input_html: { class: 'form-control' } %>
  </div>
 
  <div class="field">
    <%= form.input :top_picture, input_html: { class: 'form-control' }  %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.rich_text_area :body %>
  </div>

  <div class="actions">
    <%= form.button :submit, class: 'btn btn-info' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="posts col-md-8 col-md-offset-2">
  <div class="row">  <% @posts.each do |post| %>
  <div class="post-wrapper">
    <div class="animation-h1">
      <h1 class="ternow-h1"><%= link_to post.title, post %></h1>
      <div class="background-size">
      </div>
      <div class="background-size-4">
      </div>
      <div class="background-size-2">
      </div>
      <div class="background-size-3">
      </div>
    </div>
    <p class="post-text">
      <% if post.anouncement.nil? %>
        <%= sanitize markdown(truncate(post.body, length:150))  %>
      <% else %>
        <%= sanitize markdown(truncate(post.anouncement, length:150)) %>
      <% end %>
      </p>
    <p class="date-font-size">Posted <span class="date"><%= time_ago_in_words(post.created_at) %></span> ago</p>
    <% if post.updated_at != post.created_at %>
    <p class="date-font-size">Edited <span class="date"><%= time_ago_in_words(post.updated_at)  %></span> ago</p>
    <% end %>
    <% if user_signed_in? && current_user.id == post.user_id %>

    <li><%= link_to 'Edit', edit_post_path(post) %></li>
    <li><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></li>
    <% end %>
  </div>
  <% end %>

</div>
<%= will_paginate @posts, :page_links => false %>
 
</div>


  

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="show-page col-md-10 col-md-offset-1">
  <div class="animation-h1">
    <h1 class="ternow-h1"><%= @post.title %></h1>
    <div class="background-size">
    </div>
    <div class="background-size-4">
    </div>
    <div class="background-size-2">
    </div>
    <div class="background-size-3">
    </div>
  </div>
  <p class="post-text">
    <%= (@post.body).html_safe %>
  </p>
  <div class="show__time-links">
    <p>Posted at: <%= @post.created_at %> <br> </p>
    <p>Edited at: <%= @post.updated_at %></p>
  </div>
  <div class="show-links">
    <% if user_signed_in? %>
    <%= link_to 'Edit', edit_post_path(@post) %> |
    <% end %>
    <%= link_to 'Back', posts_path %>
  </div>

  <h3> Join Discussion: </h3>
 <div id="disqus_thread"></div>

</div>

app/views/projects/_form.html.erb
<%= simple_form_for @project, html: { multipart: true } do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">

    <%= form.input :title, input_html: { class: 'form-control' } %>
  </div>

  <div class="field">

    <%= form.input :project_picture, input_html: { class: 'form-control' }  %>
  </div>


  <div class="field">

    <%= form.input :description, input_html: { class: 'form-control' } %>

  </div>

  <div class="field">

    <%= form.input :github, input_html: { class: 'form-control' } %>

  </div>

  <div class="field">

    <%= form.input :demo, input_html: { class: 'form-control' } %>

  </div>


  <div class="actions">
    <%= form.button :submit, class: 'btn btn-info' %>
  </div>
<% end %>



app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form', project: @project %>

app/views/projects/index.html.erb

<div class="projects-section">
  <div class="animation-h1">
    <h1 class="ternow-h1">Projects</h1>
    <div class="background-size">
    </div>
    <div class="background-size-4">
    </div>
    <div class="background-size-2">
    </div>
    <div class="background-size-3">
    </div>
  </div>

</div>
</div>

<div class="projects-wrapper" style="height: <%= adaptive_height %>">


  <% @projects.each do |project| %>
  <div class="project-wrapper col-md-3 col-sm-6 col-xs-12">
    <div class="picture-overlay"></div>
    <div class="project-picture"><%= image_tag(project.project_picture.url) if project.project_picture? %></div>
    <div class="project-content">
      <h4><%= project.title %></h4>
      <p><%= project.description %></p>
      <div class="demo-button">
        <a href=<%= project.demo %>>Demo: <i class="fas fa-laptop"></i></a>

      </div>
      <div class="social">
        <a href=<%= project.github %>><i class="fab fa-github"></i></a>
      </div>
      <% if user_signed_in? && project.user_id == current_user.id %>
      <li><%= link_to 'Edit', edit_project_path(project) %></li>
      <li><%= link_to "Delete", project, method: :delete %></li>
      <% end %>
    </div>


  </div>




  <% end %>
  <div class="coming-soon col-md-3 col-sm-6 col-xs-12">
    <p><i class="fas fa-fire"></i>Coming soon...</p>

  </div>



</div>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>


app/views/rss/index.html.erb
<h1>Rss#index</h1>
<p>Find me in app/views/rss/index.html.erb</p>

app/views/static_pages/about.html.erb
<center class="col-md-offset-2 col-md-8 about">
	<div class="avatar-image-wrapper">
		<%= image_tag("avatar.png") %>
	</div>

	<p>Hi, I'm Valentine Terebenin, currently live in Smolensk and I make things for the web. 
	I'm not too bad at Ruby and Rails things, but I also do UI/UX design, minimum front-end development.</p>

	<p>In a "non-web-dev time" I usually play video-games, study electromechanics, ride velo. 
		I'm really interested in cinema, retro-games, tech books and computer science.
	</p>
	<p>Check out some things <a href=<%= posts_path %>>I've written</a> or <a href=<%= projects_path %>>projects I've done</a>.</p>
</p>
<div class="col-md-6 col-xs-12 links">
	<p>My social links:</p>
	<ul class="social">
		<li><i class="fab fa-github"></i><a href="https://github.com/Vterebenin">github</a></li>
		<li><i class="fab fa-vk"></i><a href="https://vk.com/dfkz1">vk</a></li>
		<li><i class="fab fa-telegram-plane"></i><a href="https://t.me/ternow">Telegram</a></li>
		<li><i class="fas fa-envelope"></i>email: <a href="#">ternow1@yandex.ru</a></li>
	</ul>
</div>
<div class="col-md-6 col-xs-12 thing-image-wrapper">
		<%= image_tag("the-thing.png") %>
</div>
</center>

app/views/static_pages/index.html.erb
<header>
	<div class="animation-h1">
		<h1 class="ternow-h1">WHO AM I?</h1>
		<div class="background-size">
		</div>
	</div>
	<div class="animation-h1">
		<h1 class="ternow-h1">WHO AM I?</h1>
		<div class="background-size">
		</div>
	</div>
	<div class="animation-h1">
		<h1 class="ternow-h1">WHO AM I?</h1>
		<div class="background-size">
		</div>
	</div>
	<div class="animation-h1">
		<h1 class="ternow-h1">WHO AM I?</h1>
		<div class="background-size">
		</div>
	</div>
</header>